=== openrails/content/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "@type",
            "compensation",
            "name",
            "description",
            "author",
            "image",
            "url"
        ],
        "additionalProperties": false,
        "properties": {
            "@type": {
                "type": "string",
                "enum": [
                    "https://schema.org/SoftwareApplication"
                ]
            },
            "compensation": {
                "type": "string",
                "enum": [
                    "commercial",
                    "donation",
                    "free"
                ]
            },
            "name": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "author": {
                "type": "object",
                "required": [
                    "@type",
                    "name"
                ],
                "additionalProperties": false,
                "properties": {
                    "@type": {
                        "type": "string",
                        "enum": [
                            "https://schema.org/Person",
                            "https://schema.org/Organization"
                        ]
                    },
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string",
                        "pattern": "^https?://"
                    }
                }
            },
            "image": {
                "type": "string",
                "pattern": "^https?://"
            },
            "screenshot": {
                "type": "string",
                "pattern": "^https?://"
            },
            "url": {
                "type": "string",
                "pattern": "^https?://"
            },
            "downloadSize": {
                "type": "integer",
                "minimum": 0
            },
            "installSize": {
                "type": "integer",
                "minimum": 0
            },
            "start": {
                "type": "object",
                "properties": {
                    "route": {
                        "type": "string"
                    },
                    "activity": {
                        "type": "string"
                    },                    
                    "locomotive": {
                        "type": "string"
                    },                      
                    "consist": {
                        "type": "string"
                    },                      
                    "startingAt": {
                        "type": "string"
                    },                      
                    "headingTo": {
                        "type": "string"
                    },                      
                    "time": {
                        "type": "string"
                    },                      
                    "season": {
                        "type": "string"
                    },
                    "weather": {
                        "type": "string"
                    }
                },                   
                "additionalProperties": false,
                "required": [
                    "route",
                    "activity"
                ]
            }
        }
    }
}

=== openrails/content/routes.json
[
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "BNSF Starter Route",
        "description": "Get started with Open Rails by downloading this free starter route. This route comes with trainsets and activities based on the BNSF Scenic Subdivision in the Pacific Northwest Region of the United States.",
        "author": {
            "@type": "https://schema.org/Organization",
            "name": "TrainSimulations.net",
            "url": "https://www.trainsimulations.net"
        },
        "image": "https://raw.githubusercontent.com/openrails/content/main/images/TrainSimulations.net/BNSF_starter_route.jpg",
        "screenshot": "https://www.trainsimulations.net/starter",
        "url": "https://ts-files.com/files/TS_STARTER_ROUTE.zip",
        "downloadSize": 598168814,
        "installSize": 894345725,
		    "start": {
                "route": "BNSF Scenic Sub",
                "activity": "1. What Goes Up..."
		    }
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "Burrinjuck Railway",
        "description": "The historic Burrinjuck railway, built in 1907 and decommissioned in 1929, was a narrow gauge route between Goondah and Burrinjuck in New South Wales, Australia. The line was used to transport workers, material and supplies during the construction of the Burrinjuck dam. Navigate the four German built 0-4-0 Krauss steam locomotives that transported approximately 100 tonnes of material per day, along this 26 mile / 42 km long route with challenging steep gradients.",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Peter Newell",
            "url": "https://coalstonewcastle.com.au"
        },
        "image": "https://www.burrinjuck.coalstonewcastle.com.au/screenshots/images/001-image.jpg",
        "screenshot": "https://www.burrinjuck.coalstonewcastle.com.au/screenshots/",
        "url": "https://www.burrinjuck.coalstonewcastle.com.au/",
        "downloadSize": 136713223
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "commercial",
        "name": "Canadian National - Ruel Subdivision",
        "description": "The Canadian National Railway - Ruel Subdivision is situated in early 1990â€™s Northern Ontario. In this realistic simulation you will travel around the countless lakes and rivers of the beautiful Canadian Shield, from the division point at Capreol to the small village of Foleyet. This route offers challenging activities, detailed scenery, high quality sound and accurate day and nighttime cabviews of 13 high detail Diesel Locomotive models and over 70 different freight cars.",
        "author": {
            "@type": "https://schema.org/Organization",
            "name": "TrainSimulations.net",
            "url": "https://www.trainsimulations.net"
        },
        "image": "https://raw.githubusercontent.com/openrails/content/main/images/TrainSimulations.net/CN_RUEL.jpg",
        "url": "https://www.trainsimulations.net/ruel/",
        "installSize": 1850000000
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "Chiltern",
        "description": "This route, set c.1960 in UK, includes two main and many branch lines that run through the Chiltern Hills to London as well as parts of the London Transport underground system. Also included, somewhat anachronistically, is the Shepherds Bush to Uxbridge tram route. This route is a work in progress and scenery is still being added. At the moment scenery is complete between Marylebone Station and Banbury.",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Martin Phillips",
            "url": "https://github.com/DocMartin7644"
        },
        "image": "https://raw.githubusercontent.com/DocMartin7644/Chiltern-Route-v2/main/Screenshot.jpg",
        "url": "https://github.com/DocMartin7644/Chiltern-Route-v2.git",
        "installSize": 13227601920,
        "start": {
            "route": "Chiltern",
            "activity": "RS_Let's go to Birmingham"
        }
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "Craven Timber Railway",
        "description": "The Craven Timber railway is a 5.8 miles / 9.6 km branch of the North Coast line located in New South Wales, Australia. This typical timber 'tramway' was used to transport timber out of The Glen to a sawmill located adjacent to Craven Station (180 miles north of Sydney).  Built to light railway standards with a number of tight 120m curves the line was operated by two saddle tank steam locomotives, PWD32 and 529X. It crossed the Wards River six times as it wound up the picturesque river valley.",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Peter Newell",
            "url": "http://coalstonewcastle.com.au"
        },
        "image": "http://www.craven.coalstonewcastle.com.au/screenshots/images/002-image.jpg",
        "screenshot": "http://www.craven.coalstonewcastle.com.au/screenshots/",
        "url": "http://www.craven.coalstonewcastle.com.au/"
    },
  {
    "@type": "https://schema.org/SoftwareApplication",
    "compensation": "free",
    "name": "Demo Model 1",
    "description": "Demo Model 1 is a great route to get started with Open Rails. It models the Scottish Capital Express during the 'blue' period of British Rail. Your service is a morning express from Edinburgh Waverley as far as the town of Linlithgow, about 20 minutes running. Generously donated by Making Tracks Ltd, Demo Model 1 was cut down from a full-size commercial route and contains lots of detail. Installation instructions are included. ",
    "author": {
      "@type": "https://schema.org/Organization",
      "name": "Making Tracks Ltd"
    },
    "image": "https://www.openrails.org/assets/waverley.jpg",
    "url": "https://static.openrails.org/files/DemoModel1.zip",
    "downloadSize": 272424960,
    "installSize": 336539648,
    "start": {
      "route": "Scottish Capital Express",
      "activity": "- Explore Route -",
      "locomotive": "MT Class 47706 BR Blue",
      "consist": "MT_MT_Class 47 & 6 mk2 PP",
      "startingat": "Edingburgh",
      "headingto": "Glasgow",
      "time": "12:00",
      "season": "Summer",
      "weather": "Clear"
    }
  },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "Great Zig Zag Railway - New South Wales",
        "description": "The Great Zig Zag railway between Mt Victoria and Bowenfels, west of Lithgow, New South Wales, Australia, was part of the Great Western line that connects Sydney with Western New South Wales. The line, hailed as an international engineering marvel in the late 19th century, was the most cost effective solution to traverse the Blue Mountains, west of Sydney. This route comes with 7 tutorial activities that introduce you progressively to the challenges of managing a Steam-hauled train. ",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Peter Newell",
            "url": "http://coalstonewcastle.com.au"
        },
        "image": "http://www.zigzag.coalstonewcastle.com.au/screenshots/images/001-image.jpg",
        "screenshot": "http://www.zigzag.coalstonewcastle.com.au/screenshots/",
        "url": "http://www.zigzag.coalstonewcastle.com.au/",
        "downloadSize": 210074550
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "Manning River Breakwall Railway",
        "description": "The Manning River Breakwater railway was built in 1895 to transport rock from a quarry at Crowdy Head to the entrance of the river at Harrington. Powered by a Baldwin Steam Tram motor, approximately 600,000 tons of rock was transported over time from the quarry to Harrington.  Operation of this route was relatively simple as it was fairly flat with a single locomotive, so that signalling was not required.",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Peter Newell",
            "url": "http://coalstonewcastle.com.au"
        },
        "image": "http://www.manning-river.coalstonewcastle.com.au/screenshots/images/002-image.jpg",
        "screenshot": "http://www.manning-river.coalstonewcastle.com.au/screenshots/",
        "url": "http://www.manning-river.coalstonewcastle.com.au/",
        "downloadSize": 74799426
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "free",
        "name": "MidEast Coast",
        "description": "This route is a \"work in progress\" by Mick Clarke and set in 1950's UK. It runs from London northwards to York and includes the lines to Hunstanton and Skegness as well as many of the East Midlands and Yorkshire coal mines. Further extensions are planned. It is a refinement of MidEast Plus which was written for MSTS and set in the 1970's. (Size about 4GB but growing)",
        "author": {
            "@type": "https://schema.org/Person",
            "name": "Mick Clarke"
        },
        "image": "https://raw.githubusercontent.com/MECoast/MECoast/main/GitHub_assets/Spilsby.jpg",
        "url": "https://github.com/MECoast/MECoast.git",
        "installSize": 8290103296,
        "start": {
            "route": "MIDEAST COAST 1.6.7.5 (13 MAR 2024)-3 New Class J69 Locos added. Minor errors corrected",
            "activity": "MC-SunnyHunny"
        }
    },
    {
        "@type": "https://schema.org/SoftwareApplication",
        "compensation": "commercial",
        "name": "Montana Rail Link - Mullan Pass",
